services:
  app:
    container_name: open-directory
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./open-directory:/app
    depends_on:
      - mongodb
      - mysql
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_USER=breaze
      - MONGO_PASSWORD=12345678
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=12345678
    networks:
      - network-open-directory
  mongodb:
    container_name: mongo-open-directory
    image: mongo
    ports:
      - "27017:2017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=breaze
      - MONGO_INITDB_ROOT_PASSWORD=12345678
    volumes:
      - data_mongo:/data/db
    networks:
      - network-open-directory
  mysql:
    container_name: mysql-open-directory
    image: mysql:8.4.4
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
    volumes:
      - data_mysql:/var/lib/mysql
    networks:
      - network-open-directory
volumes:
  data_mongo:
  data_mysql:
networks:
  network-open-directory: